### ISSUE TITLE
Version 0.0.6 on npm

### ISSUE THREAD

**Issue by hhaidar** [qesuto/node-krb5#12]
Hi,

Are there plans to publish the next version on NPM soon? I'd love to be able to use this on node 0.12

Thanks :D

**Comment by qesuto** [comment]
done

**Comment by hhaidar** [comment]
thanks @qesuto

**Comment by qesuto** [comment]
T'ha k

**Comment by qesuto** [comment]
Oops, thanks to recent PR contributors. So little time to take care of this nowadays...
